### ISSUE TITLE
masking the 'not a number' pixels for the input images.

### ISSUE THREAD

**Issue by shuaigezhu** [shuaigezhu/star_galaxy_classification#25]

**Comment by shuaigezhu** [comment]
![Screen Shot 2020-04-01 at 10 20 40 AM](https://user-images.githubusercontent.com/47727949/78167152-d7f2ed80-7402-11ea-8996-f7385ca86ff6.png)

The issue is the images may have no information in some pixels. We can see there is a stripe in g, i, z bands. Currently, I just assign -1 to fill up the pixels and use 0 weight to train, but I hope there is a way to mask it during prediction.

**Comment by kmyi** [comment]
Hi Yufeng, I'm going to use this image in our website. Hope that's fine with you.

**Comment by shuaigezhu** [comment]
> Hi Yufeng, I'm going to use this image in our website. Hope that's fine with you.

Yes, of course.
