### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by kmyi** [shuaigezhu/star_galaxy_classification#35]

**Comment by shuaigezhu** [comment]
there are 267 objects in the test set:
1. KL (background and label pixel)
![test](https://user-images.githubusercontent.com/47727949/79153128-36fd1e80-7d82-11ea-9e43-eac9cc3addd1.png)

2. KL (background and label pixel + weighted class)
![test](https://user-images.githubusercontent.com/47727949/79153192-4f6d3900-7d82-11ea-83d2-69ddfcfe9bd7.png)

3. KL (background and label pixel + gaussian blur)
![test](https://user-images.githubusercontent.com/47727949/79153240-60b64580-7d82-11ea-8364-66ace4955a2a.png)

4. MSE (background and label pixel)
![test](https://user-images.githubusercontent.com/47727949/79153266-70358e80-7d82-11ea-9247-8efffacfeddd.png)

5. MSE (background and label pixel + weighted class)
![test](https://user-images.githubusercontent.com/47727949/79153343-8cd1c680-7d82-11ea-8bc6-c9e258fffef9.png)

6. MSE (background and label pixel + gaussian blur)
![test](https://user-images.githubusercontent.com/47727949/79153376-9b1fe280-7d82-11ea-8c57-b3f7fc82baf5.png)
