### ISSUE TITLE
use SK-Learn to show Normalized Confusion Matrix

### ISSUE THREAD

**Issue by shuaigezhu** [shuaigezhu/star_galaxy_classification#39]

**Comment by shuaigezhu** [comment]
confusion matrix
![cm](https://user-images.githubusercontent.com/47727949/79285276-ed8bfc80-7e71-11ea-8587-37412dc5c7e5.png)

Normalized confusion matrix
![cmn](https://user-images.githubusercontent.com/47727949/79285280-f41a7400-7e71-11ea-9e64-77bebb5c7faf.png)

**Comment by kmyi** [comment]
Wait, how come you only have the positives? You should also have negatives in this confusion matrix…

--
Kwang Moo YI
Assistant Professor
Dept. of Computer Science
University of Victoria
+1 (250) 472 5837
